[package]
name = "mars-app"
version = "0.5.0"
description = "Mars is a cryptocurrency for sovereign individuals living in Mirascape Horizon across the galaxy."
edition = "2021"
license = "Apache-2.0"
homepage = "https://mars.miraland.io"
documentation = "https://mars.miraland.io"
repository = "https://github.com/miraland-labs/mars-app"
readme = "./README.md"
keywords = ["solana", "crypto", "mining", "mars", "miraland"]

[features]
default = ["web"]
bundle = []
desktop = [
    "async-tungstenite",
    "dioxus-desktop",
    "directories",
    "env_logger",
    "home",
    "num_cpus",
    "solana-account-decoder",
    "solana-client",
    "solana-sdk",
    "solana-transaction-status",
    "spl-memo",
    "spl-token",
    "spl-associated-token-account",
]
web = [
    "dioxus-web",
    "gloo",
    "gloo-storage",
    "js-sys",
    "serde-wasm-bindgen",
    "solana-client-wasm",
    "solana-extra-wasm",
    "wasm-bindgen",
    "wasm-bindgen-futures",
    "wasm-logger",
    "web-sys",
    "web-time",
]

[dependencies]
async-std = "1.12.0"
async-tungstenite = { version = "0.25.0", features = ["async-std-runtime", "async-native-tls"], optional = true }
bincode = "1.3.3"
cached = "0.47.0"
chrono = "0.4.34"
dioxus = "0.4.3"
dioxus-desktop = { version = "0.4.3", optional = true }
dioxus-router = "0.4.3"
dioxus-std = { version = "0.4.1", features = ["clipboard", "utils"] }
dioxus-web = { version = "0.4.3", optional = true }
directories = { version = "4.0.1", optional = true }
env_logger = { version = "0.11.2", optional = true }
futures = "0.3.30"
gloo = { version = "0.11.0", optional = true }
gloo-storage = { version = "0.3.0", optional = true }
home = { verison = "0.5.9", optional = true }
is-url = { version = "1.0.4" }
js-sys = { version = "0.3.67", optional = true }
log = "0.4.20"
num_cpus = { version = "1.16.0", optional = true }
mars = { package = "mars-program", version = "1.0.0", features = ["no-entrypoint"] }
ore-types = "0.0.5"
qrcode-generator = "4.1.9"
rand = "0.8.5"
reqwest = "0.11.24"
serde = { version = "1.0", features = ["derive"] }
serde-wasm-bindgen = { version = "0.6.3", optional = true }
serde_json = "1.0"
solana-account-decoder = { version = "1.17.4", optional = true }
solana-client = { verison = "1.17.4", optional = true }
solana-client-wasm = { version = "1.17.4", optional = true }
solana-extra-wasm = { version = "1.17.4", optional = true }
solana-sdk = { version = "1.17.4", optional = true }
solana-transaction-status = { version = "1.17.4", optional = true }
spl-memo = { version = "^4", features = ["no-entrypoint"], optional = true }
spl-token = { version = "^4", features = ["no-entrypoint"], optional = true }
spl-associated-token-account = { version = "^2.2", features = [ "no-entrypoint" ], optional = true }
url = "2.5.0"
wasm-bindgen = { version = "0.2.91", optional = true }
wasm-bindgen-futures = { version = "0.4.41", optional = true }
wasm-logger = { version = "0.2.0", optional = true }
web-time = { version = "1.0.0", optional = true }

[dependencies.web-sys]
version = "0.3"
optional = true
features = [
    'console',
    'Clipboard',
    'Document',
    'HtmlElement',
    'HtmlInputElement',
    'MessageEvent',
    'Navigator',
    'Window',
    'Worker',
    'WorkerOptions',
    'WorkerType',
    'WorkerGlobalScope',
]

[patch.crates-io]
solana-client-wasm = { version = "1.17.4", git = "https://github.com/HardhatChad/solana-playground", branch = "hardhatchad/token-largest" }
solana-extra-wasm = { version = "1.17.4", git = "https://github.com/HardhatChad/solana-playground", branch = "hardhatchad/token-largest" }
# solana-client-wasm = { version = "1.17.4", git = "https://github.com/HardhatChad/solana-playground", rev = "91367320c2f76d9d6e24e55f48eb14b7947b1c8f" }
# solana-extra-wasm = { version = "1.17.4", git = "https://github.com/HardhatChad/solana-playground", rev = "91367320c2f76d9d6e24e55f48eb14b7947b1c8f" }

[package.metadata.bundle]
name = "Mars"
identifier = "com.mars.app"
version = "0.5.0"
resources = ["public"]
copyright = "Copyright (c) Miraland Labs 2024. All rights reserved."
category = "Finance"
short_description = "Mars miner"
long_description = "Mars is a cryptocurrency for sovereign individuals living in Mirascape Horizon across the galaxy."
osx_url_schemes = ["com.mars.app"]
info_plist = "Info.plist"
icon = ["Icon.icns"]
